#!/usr/bin/env python3
"""Print the LR/epoch sweep dump as CSV rows."""

from __future__ import annotations

import argparse
import csv
import math
import pickle
import sys
from pathlib import Path
from typing import Iterable


DEFAULT_METRIC_COLUMNS = [
    "fidelity",
    "explanation_size",
    "num_cf_found",
    "fidelity_denominator",
    "num_targets",
    "num_non_isolated",
    "num_cf_possible",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert the lrepoch.py aggregate pickle dump to CSV."
    )
    parser.add_argument(
        "--dump",
        "--results",
        dest="dump",
        required=True,
        help="Path to the .pkl file generated by lrepoch.py.",
    )
    return parser.parse_args()


def format_number(value: object) -> str:
    if value is None:
        return "NA"
    if isinstance(value, bool):
        return str(value)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            return "NA"
        if value.is_integer():
            return str(int(value))
        return f"{value:.6g}"
    return str(value)


def load_dump(dump_path: Path) -> object:
    if not dump_path.exists():
        raise FileNotFoundError(f"Dump file not found: {dump_path}")
    with dump_path.open("rb") as handle:
        return pickle.load(handle)


def get_runs(payload: object) -> list[dict[str, object]]:
    default_strategy = None
    if isinstance(payload, dict):
        runs = payload.get("runs")
        if runs is None:
            raise ValueError("Dump does not contain a 'runs' entry.")
        strategy_value = payload.get("strategy")
        if isinstance(strategy_value, str):
            default_strategy = strategy_value
    else:
        runs = payload

    if not isinstance(runs, list):
        raise ValueError("Dump 'runs' entry must be a list.")

    normalized: list[dict[str, object]] = []
    for index, run in enumerate(runs):
        if not isinstance(run, dict):
            raise ValueError(f"Run entry {index} is not a dictionary.")
        normalized_run = dict(run)
        metrics = normalized_run.get("metrics", {})
        if not isinstance(metrics, dict):
            metrics = {}
        if "strategy" not in normalized_run and default_strategy is not None:
            normalized_run["strategy"] = default_strategy
        if "denominator_scope" not in normalized_run:
            normalized_run["denominator_scope"] = metrics.get(
                "denominator_scope",
                "non_isolated",
            )
        normalized.append(normalized_run)
    return normalized

def metric_columns(runs: Iterable[dict[str, object]]) -> list[str]:
    columns = list(DEFAULT_METRIC_COLUMNS)
    seen = set(columns)
    for run in runs:
        metrics = run.get("metrics", {})
        if not isinstance(metrics, dict):
            continue
        for key in metrics:
            key_text = str(key)
            if key_text not in seen:
                columns.append(key_text)
                seen.add(key_text)
    return columns


def run_sort_key(run: dict[str, object]) -> tuple[int, int, float, int]:
    strategy_order = {"v1": 0, "v3": 1}
    scope_order = {"non_isolated": 0, "possible": 1}
    strategy = str(run.get("strategy", ""))
    scope = str(run.get("denominator_scope", "non_isolated"))
    lr = run.get("lr", run.get("learning_rate", 0.0))
    epoch = run.get("epoch", run.get("epochs", 0))
    return (
        strategy_order.get(strategy, len(strategy_order)),
        scope_order.get(scope, len(scope_order)),
        float(lr),
        int(epoch),
    )

def write_csv(runs: list[dict[str, object]]) -> None:
    columns = metric_columns(runs)
    writer = csv.writer(sys.stdout, lineterminator="\n")
    writer.writerow(["strategy", "denominator_scope", "lr", "epoch", *columns])
    for run in sorted(runs, key=run_sort_key):
        metrics = run.get("metrics", {})
        if not isinstance(metrics, dict):
            metrics = {}
        lr = run.get("lr", run.get("learning_rate"))
        epoch = run.get("epoch", run.get("epochs"))
        writer.writerow(
            [
                format_number(run.get("strategy", "NA")),
                format_number(run.get("denominator_scope", "non_isolated")),
                format_number(lr),
                format_number(epoch),
                *[format_number(metrics.get(column)) for column in columns],
            ]
        )

def main() -> None:
    args = parse_args()
    payload = load_dump(Path(args.dump))
    write_csv(get_runs(payload))


if __name__ == "__main__":
    main()
