import argparse
import pickle
import os
import re
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F

def parse_args():
    parser = argparse.ArgumentParser(
        description="Evaluate CF-HyperGNNExplainer results"
    )
    parser.add_argument(
        "--results",
        type=str,
        required=True,
        help="Path to the .pkl file generated by main_explain.py",
    )
    parser.add_argument(
        "--strategy",
        type=str,
        default="v1",
        choices=["v1", "v3"],
        help="Strategy to evaluate (v1: entry-wise difference, v3: hyperedge-wise difference)",
    )
    return parser.parse_args()


def get_incidence_diff(sub_H_sparse, cf_H_sparse):
    """
    Calculates the exact discrete difference between
    the original subgraph and the counterfactual.
    """
    sub_dense = sub_H_sparse.to_dense().cpu()
    cf_dense = cf_H_sparse.to_dense().cpu()

    diff = torch.abs(sub_dense - cf_dense)
    diff = (diff > 1e-5).float()

    num_diffs = torch.sum(diff).item()
    num_entries = torch.sum(sub_dense).item()

    return num_diffs, num_entries


def get_hyperedge_diff(sub_H_sparse, cf_H_sparse, eps=1e-5):
    """
    Counts how many hyperedges present in `sub_H_sparse` were completely removed
    in `cf_H_sparse`.
    """
    sub_H_sparse = sub_H_sparse.coalesce()
    cf_H_sparse = cf_H_sparse.coalesce()

    sub_indices = sub_H_sparse.indices()
    if sub_indices.numel() == 0:
        return 0, 0

    sub_cols = torch.unique(sub_indices[1]).cpu().tolist()
    total_hyperedges = len(sub_cols)

    cf_indices = cf_H_sparse.indices()
    cf_values = cf_H_sparse.values()

    if cf_indices.numel() == 0:
        present_cf_cols = set()
    else:
        nonzero_mask = cf_values.abs() > eps
        if nonzero_mask.any():
            present_cf_cols = set(cf_indices[1][nonzero_mask].cpu().tolist())
        else:
            present_cf_cols = set()

    removed_hyperedges = sum(1 for c in sub_cols if c not in present_cf_cols)

    return removed_hyperedges, total_hyperedges


def extract_dataset_name(results_path: str) -> str:
    result_name = os.path.splitext(os.path.basename(results_path))[0]
    match = re.match(r"^cf_examples?_(.+?)_\d{8}-\d{6}(?:_.+)?$", result_name)
    if match:
        return match.group(1)

    for prefix in ("cf_examples_", "cf_example_"):
        if result_name.startswith(prefix):
            remainder = result_name[len(prefix):]
            return remainder.split("_", 1)[0]

    return result_name


def summarize_values(values) -> tuple[float | None, float | None]:
    array = np.asarray(values, dtype=float)
    array = array[np.isfinite(array)]

    if array.size == 0:
        return None, None

    mean = float(np.mean(array))
    std = float(np.std(array, ddof=1)) if array.size > 1 else None
    return mean, std


def format_number(value) -> str:
    if value is None:
        return "NA"

    number = float(value)
    if not np.isfinite(number):
        return "NA"

    if number.is_integer():
        return str(int(number))

    return f"{number:.6g}"


def format_summary(values) -> str:
    mean, std = summarize_values(values)
    if mean is None:
        return "NA"
    if std is None:
        return format_number(mean)
    return f"{format_number(mean)} +/- {format_number(std)}"


def get_result_header(example_width: int) -> list[str]:
    if example_width == 15:
        return [
            "node_idx",
            "new_idx",
            "cf_H",
            "sub_H",
            "y_pred_orig",
            "y_pred_new",
            "y_pred_new_actual",
            "label",
            "num_nodes",
            "loss_total",
            "loss_pred",
            "loss_graph_dist_training",
            "log_prob_orig",
            "log_prob_new",
            "log_prob_new_actual",
        ]

    if example_width == 12:
        return [
            "node_idx",
            "new_idx",
            "cf_H",
            "sub_H",
            "y_pred_orig",
            "y_pred_new",
            "y_pred_new_actual",
            "label",
            "num_nodes",
            "loss_total",
            "loss_pred",
            "loss_graph_dist_training",
        ]

    raise ValueError(f"Unsupported result row width: {example_width}")


def compute_shypx_metrics(df: pd.DataFrame):
    """Compute SHypX-style fidelity metrics for successful counterfactuals."""
    required_columns = {"log_prob_orig", "log_prob_new", "y_pred_orig", "y_pred_new"}
    if not required_columns.issubset(df.columns):
        return None

    metrics = {
        "fid_plus_acc": [],
        "fid_plus_kl": [],
        "fid_plus_tv": [],
        "fid_plus_xent": [],
    }

    eps = 1e-10

    for i in df.index:
        log_prob_orig = df["log_prob_orig"][i]
        log_prob_new = df["log_prob_new"][i]

        p_orig = torch.exp(log_prob_orig).clamp(min=eps)
        p_expl = torch.exp(log_prob_new).clamp(min=eps)

        y_pred_orig = df["y_pred_orig"][i]
        y_pred_expl = df["y_pred_new"][i]

        metrics["fid_plus_acc"].append(float(y_pred_orig != y_pred_expl))

        kl_div = F.kl_div(p_orig.log(), p_expl, reduction="sum").item()
        metrics["fid_plus_kl"].append(max(kl_div, 0.0))

        tv_dist = 0.5 * torch.sum(torch.abs(p_expl - p_orig))
        metrics["fid_plus_tv"].append(tv_dist.item())

        xent = -torch.sum(p_orig * torch.log(p_expl))
        metrics["fid_plus_xent"].append(xent.item())

    return metrics


def main():
    args = parse_args()
    dataset_name = extract_dataset_name(args.results)

    if not os.path.exists(args.results):
        raise FileNotFoundError(f"Results file not found: {args.results}")

    with open(args.results, "rb") as f:
        cf_examples_per_node = pickle.load(f)

    df_prep = []
    total_attempts = len(cf_examples_per_node)

    for example in cf_examples_per_node:
        if example:
            df_prep.append(example[0])

    example_width = len(df_prep[0]) if df_prep else None
    header = get_result_header(example_width) if example_width is not None else []

    df = pd.DataFrame(df_prep, columns=header)

    num_cf_found = len(df)
    avg_fidelity = 1 - num_cf_found / total_attempts if total_attempts > 0 else None
    csv_header = [
        "dataset",
        "num_cf_found",
        "avg_fidelity",
        "graph_distance",
        "sparsity",
        "fid_plus_acc",
        "fid_plus_kl",
        "fid_plus_tv",
        "fid_plus_xent",
    ]

    if df.empty:
        csv_values = [
            dataset_name,
            str(num_cf_found),
            format_number(avg_fidelity),
            "NA",
            "NA",
            "NA",
            "NA",
            "NA",
            "NA",
        ]
        print(",".join(csv_header))
        print(",".join(csv_values))
        return

    graph_distances = []
    num_incidence_entries = []

    for i in df.index:
        cf_H = df["cf_H"][i]
        sub_H = df["sub_H"][i]

        if args.strategy == "v3":
            dist, entries = get_hyperedge_diff(sub_H, cf_H)
        else:
            dist, entries = get_incidence_diff(sub_H, cf_H)

        graph_distances.append(dist)
        num_incidence_entries.append(entries)

    df["graph_dist"] = graph_distances
    df["num_entries"] = num_incidence_entries

    # Check consistency between predictions and log-probabilities when present.
    if {"log_prob_orig", "log_prob_new", "log_prob_new_actual"}.issubset(df.columns):
        for i in df.index:
            log_prob_orig = df["log_prob_orig"][i]
            pred_from_log_prob_orig = torch.argmax(log_prob_orig).item()
            assert (
                df["y_pred_orig"][i] == pred_from_log_prob_orig
            ), f"Inconsistent original prediction at index {i}: y_pred_orig={df['y_pred_orig'][i]}, pred_from_log_prob_orig={pred_from_log_prob_orig}"

            y_pred_new = df["y_pred_new"][i]
            y_pred_new_actual = df["y_pred_new_actual"][i]
            log_prob_new = df["log_prob_new"][i]
            log_prob_new_actual = df["log_prob_new_actual"][i]

            pred_from_log_prob = torch.argmax(log_prob_new).item()
            pred_from_log_prob_actual = torch.argmax(log_prob_new_actual).item()

            assert (
                y_pred_new == pred_from_log_prob
            ), f"Inconsistent prediction at index {i}: y_pred_new={y_pred_new}, pred_from_log_prob={pred_from_log_prob}"
            assert (
                y_pred_new_actual == pred_from_log_prob_actual
            ), f"Inconsistent actual prediction at index {i}: y_pred_new_actual={y_pred_new_actual}, pred_from_log_prob_actual={pred_from_log_prob_actual}"

    sparsity_values = [
        1 - graph_dist / num_entries if num_entries > 0 else np.nan
        for graph_dist, num_entries in zip(df["graph_dist"], df["num_entries"])
    ]
    shypx_metrics = compute_shypx_metrics(df)

    csv_values = [
        dataset_name,
        str(num_cf_found),
        format_number(avg_fidelity),
        format_summary(df["graph_dist"]),
        format_summary(sparsity_values),
        format_summary(shypx_metrics["fid_plus_acc"]) if shypx_metrics else "NA",
        format_summary(shypx_metrics["fid_plus_kl"]) if shypx_metrics else "NA",
        format_summary(shypx_metrics["fid_plus_tv"]) if shypx_metrics else "NA",
        format_summary(shypx_metrics["fid_plus_xent"]) if shypx_metrics else "NA",
    ]

    print(",".join(csv_header))
    print(",".join(csv_values))


if __name__ == "__main__":
    main()
