import argparse
import pickle
import os
import numpy as np
import pandas as pd
import torch


def parse_args():
    parser = argparse.ArgumentParser(
        description="Evaluate CF-HyperGNNExplainer results"
    )
    parser.add_argument(
        "--results",
        type=str,
        required=True,
        help="Path to the .pkl file generated by main_explain.py",
    )
    parser.add_argument(
        "--strategy",
        type=str,
        default="v1",
        choices=["v1", "v3"],
        help="Strategy to evaluate (v1: entry-wise difference, v3: hyperedge-wise difference)",
    )
    return parser.parse_args()


def get_incidence_diff(sub_H_sparse, cf_H_sparse):
    """
    Calculates the exact discrete difference between
    the original subgraph and the counterfactual.
    """
    sub_dense = sub_H_sparse.to_dense().cpu()
    cf_dense = cf_H_sparse.to_dense().cpu()

    diff = torch.abs(sub_dense - cf_dense)
    diff = (diff > 1e-5).float()

    num_diffs = torch.sum(diff).item()
    num_entries = torch.sum(sub_dense).item()

    return num_diffs, num_entries


def get_hyperedge_diff(sub_H_sparse, cf_H_sparse, eps=1e-5):
    """
    Counts how many hyperedges present in `sub_H_sparse` were completely removed
    in `cf_H_sparse`.
    """
    sub_H_sparse = sub_H_sparse.coalesce()
    cf_H_sparse = cf_H_sparse.coalesce()

    sub_indices = sub_H_sparse.indices()
    if sub_indices.numel() == 0:
        return 0, 0

    sub_cols = torch.unique(sub_indices[1]).cpu().tolist()
    total_hyperedges = len(sub_cols)

    cf_indices = cf_H_sparse.indices()
    cf_values = cf_H_sparse.values()

    if cf_indices.numel() == 0:
        present_cf_cols = set()
    else:
        nonzero_mask = cf_values.abs() > eps
        if nonzero_mask.any():
            present_cf_cols = set(cf_indices[1][nonzero_mask].cpu().tolist())
        else:
            present_cf_cols = set()

    removed_hyperedges = sum(1 for c in sub_cols if c not in present_cf_cols)

    return removed_hyperedges, total_hyperedges


def main():
    args = parse_args()

    if not os.path.exists(args.results):
        raise FileNotFoundError(f"Results file not found: {args.results}")

    with open(args.results, "rb") as f:
        cf_examples_per_node = pickle.load(f)

    header = [
        "node_idx",
        "new_idx",
        "cf_H",
        "sub_H",
        "y_pred_orig",
        "y_pred_new",
        "y_pred_new_actual",
        "label",
        "num_nodes",
        "loss_total",
        "loss_pred",
        "loss_graph_dist_training",
    ]

    df_prep = []
    total_attempts = len(cf_examples_per_node)

    for example in cf_examples_per_node:
        if example:
            df_prep.append(example[0])

    df = pd.DataFrame(df_prep, columns=header)

    if df.empty:
        print("No successful counterfactual examples found.")
        return

    graph_distances = []
    num_incidence_entries = []

    for i in df.index:
        cf_H = df["cf_H"][i]
        sub_H = df["sub_H"][i]

        if args.strategy == "v3":
            dist, entries = get_hyperedge_diff(sub_H, cf_H)
        else:
            dist, entries = get_incidence_diff(sub_H, cf_H)

        graph_distances.append(dist)
        num_incidence_entries.append(entries)

    df["graph_dist"] = graph_distances
    df["num_entries"] = num_incidence_entries

    print(args.results)
    print("Num cf examples found: {}/{}".format(len(df), total_attempts))

    print("Avg fidelity: {}".format(1 - len(df) / total_attempts))

    metric_name = "hyperedges removed" if args.strategy == "v3" else "entries changed"
    print(
        "Average graph distance ({}): {}, std: {}".format(
            metric_name, np.mean(df["graph_dist"]), np.std(df["graph_dist"])
        )
    )

    print(
        "Average sparsity: {}, std: {}".format(
            np.mean(1 - df["graph_dist"] / df["num_entries"]),
            np.std(1 - df["graph_dist"] / df["num_entries"]),
        )
    )

    print(" ")
    print("***************************************************************")
    print(" ")


if __name__ == "__main__":
    main()
