import argparse
import os
import pickle
from typing import List

import numpy as np
import torch


# Fid+_Acc   — fraction of prediction mismatches                       (↑ better)
# Fid+_KL    — KL(p_comp\expl ‖ p_orig)                                (↑ better)
# Fid+_TV    — 1/2 * ||p_comp\expl - p_orig||_1                        (↑ better)
# Fid+_Xent  — H(p_comp\expl, p_orig) = -Σ p_comp\expl log p_orig      (↑ better)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate SHypX results with generalized fidelity+ metrics "
            "on complement subhypergraphs."
        )
    )
    parser.add_argument(
        "--results",
        type=str,
        required=True,
        help="Path to the .pkl file generated by main_shypx.py",
    )
    parser.add_argument(
        "--complement-log-key",
        type=str,
        default="log_p_comp_minus_expl",
        help=(
            "Key in each result dict containing log-probabilities for "
            "f(G_comp \\ G_expl, X, v)."
        ),
    )
    return parser.parse_args()


def compute_metrics(results: List, complement_log_key: str) -> None:
    """Compute and print fidelity+ metrics."""
    non_null = [r for r in results if r is not None]
    total = len(results)

    valid = [
        r
        for r in non_null
        if "log_p_orig" in r
        and complement_log_key in r
        and r[complement_log_key] is not None
    ]

    if not non_null:
        print("No valid results to evaluate.")
        return

    if not valid:
        print(
            "No result entry contains complement logits required for fidelity+ "
            f"(missing key: '{complement_log_key}')."
        )
        print("\nRequired upstream change (do not apply here):")
        print(
            "  Store f(G_comp \\ G_expl, X, v) log-probabilities in each result "
            f"dict under '{complement_log_key}'."
        )
        return

    N = len(valid)
    missing = len(non_null) - N

    fidp_acc: list[float] = []
    fidp_kl: list[float] = []
    fidp_tv: list[float] = []
    fidp_xent: list[float] = []

    eps = 1e-10

    for r in valid:
        log_p_comp_minus_expl: torch.Tensor = r[complement_log_key]
        log_p_orig: torch.Tensor = r["log_p_orig"]

        p_comp_minus_expl = log_p_comp_minus_expl.exp().clamp(min=eps)
        p_orig = log_p_orig.exp().clamp(min=eps)

        y_comp_minus_expl = p_comp_minus_expl.argmax().item()
        y_orig = p_orig.argmax().item()
        fidp_acc.append(float(y_comp_minus_expl != y_orig))

        kl = (p_comp_minus_expl * (p_comp_minus_expl / p_orig).log()).sum().item()
        fidp_kl.append(max(kl, 0.0))

        tv = 0.5 * (p_comp_minus_expl - p_orig).abs().sum().item()
        fidp_tv.append(tv)

        xent = -(p_comp_minus_expl * p_orig.log()).sum().item()
        fidp_xent.append(xent)

    print(f"\nSHypX fidelity+ evaluation  ({N} / {total} nodes with usable entries)\n")
    if missing > 0:
        print(f"Skipped {missing} non-null result(s) missing '{complement_log_key}'.\n")

    print(f"  {'Metric':<22} {'Mean':>10} {'Std':>10}")
    print("  " + "-" * 44)

    for name, vals in [
        ("Fid+_Acc  (↑)", fidp_acc),
        ("Fid+_KL   (↑)", fidp_kl),
        ("Fid+_TV   (↑)", fidp_tv),
        ("Fid+_Xent (↑)", fidp_xent),
    ]:
        m, s = float(np.mean(vals)), float(np.std(vals))
        print(f"  {name:<22} {m:>10.4f} {s:>10.4f}")

    print()


def main() -> None:
    args = parse_args()

    if not os.path.exists(args.results):
        raise FileNotFoundError(f"Results file not found: {args.results}")

    with open(args.results, "rb") as f:
        results = pickle.load(f)

    compute_metrics(results, args.complement_log_key)


if __name__ == "__main__":
    main()
