import argparse
import os
import pickle
from typing import List

import numpy as np
import torch


# Fid-_Acc   — fraction of prediction mismatches                       (↓ better)
# Fid-_KL    — KL(p_expl ‖ p_orig)                                    (↓ better)
# Fid-_TV    — 1/2 * ||p_expl - p_orig||_1                            (↓ better)
# Fid-_Xent  — H(p_expl, p_orig) = -Σ p_expl log p_orig                (↓ better)
# Size        — average |G_expl|₁  (node-hyperedge links)   (↓ better)
# Density     — average |G_expl|₁ / |G_comp|₁               (↓ better)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate SHypX results with generalized fidelity- metrics "
            "on explanation subhypergraphs."
        )
    )
    parser.add_argument(
        "--results",
        type=str,
        required=True,
        help="Path to the .pkl file generated by main_shypx.py",
    )
    return parser.parse_args()


def compute_metrics(results: List) -> None:
    """Compute and print all fidelity and concision metrics."""
    non_null = [r for r in results if r is not None]
    isolated = sum(1 for r in non_null if r.get("num_links_comp", 0) == 0)
    valid = [r for r in non_null if r.get("num_links_comp", 0) > 0]
    total = len(results)

    if not valid:
        print("No valid results to evaluate.")
        return

    N = len(valid)

    fid_acc: list[float] = []
    fid_kl: list[float] = []
    fid_tv: list[float] = []
    fid_xent: list[float] = []
    sizes: list[float] = []
    densities: list[float] = []

    eps = 1e-10

    for r in valid:
        log_p_expl: torch.Tensor = r["log_p_expl"]
        log_p_orig: torch.Tensor = r["log_p_orig"]

        p_expl = log_p_expl.exp().clamp(min=eps)
        p_orig = log_p_orig.exp().clamp(min=eps)

        y_expl = p_expl.argmax().item()
        y_orig = p_orig.argmax().item()
        fid_acc.append(float(y_expl != y_orig))

        kl = (p_expl * (p_expl / p_orig).log()).sum().item()
        fid_kl.append(max(kl, 0.0))

        tv = 0.5 * (p_expl - p_orig).abs().sum().item()
        fid_tv.append(tv)

        xent = -(p_expl * p_orig.log()).sum().item()
        fid_xent.append(xent)

        sizes.append(float(r["num_links_expl"]))
        comp = r["num_links_comp"]
        densities.append(r["num_links_expl"] / comp if comp > 0 else 0.0)

    print(f"\nSHypX fidelity- evaluation  ({N} / {total} valid)\n")
    if isolated > 0:
        print(f"Excluded {isolated} isolated node(s) (num_links_comp == 0) from the average.\n")
    print(f"  {'Metric':<22} {'Mean':>10} {'Std':>10}")
    print("  " + "-" * 44)

    for name, vals in [
        ("Fid-_Acc  (↓)", fid_acc),
        ("Fid-_KL   (↓)", fid_kl),
        ("Fid-_TV   (↓)", fid_tv),
        ("Fid-_Xent (↓)", fid_xent),
        ("Size       (↓)", sizes),
        ("Density    (↓)", densities),
    ]:
        m, s = float(np.mean(vals)), float(np.std(vals))
        print(f"  {name:<22} {m:>10.4f} {s:>10.4f}")

    print()


def main() -> None:
    args = parse_args()

    if not os.path.exists(args.results):
        raise FileNotFoundError(f"Results file not found: {args.results}")

    with open(args.results, "rb") as f:
        results = pickle.load(f)

    compute_metrics(results)


if __name__ == "__main__":
    main()
