import argparse
import os
import pickle

import numpy as np
import pandas as pd
import torch


def parse_args():
    parser = argparse.ArgumentParser(
        description="Evaluate CF-HyperGNNExplainer results"
    )
    parser.add_argument(
        "--results",
        type=str,
        required=True,
        help="Path to the .pkl file generated by main_explain.py",
    )
    parser.add_argument(
        "--strategy",
        type=str,
        default="v1",
        choices=["v1", "v3"],
        help="Strategy to evaluate (v1: entry-wise difference, v3: hyperedge-wise difference)",
    )
    return parser.parse_args()


def _to_2d_tensor(x) -> torch.Tensor:
    if isinstance(x, torch.Tensor):
        tensor = x
    else:
        tensor = torch.as_tensor(x)

    if tensor.numel() == 0:
        return tensor.reshape(0, 0)

    if tensor.dim() == 1:
        return tensor.reshape(1, -1)

    return tensor


def get_incidence_diff(sub_H_dense, cf_H_dense):
    """
    Calculates the exact discrete difference between
    the original subgraph and the counterfactual.

    Dense equivalent of src_sparse/evaluate.py:get_incidence_diff.
    """
    sub_dense = _to_2d_tensor(sub_H_dense).cpu().float()
    cf_dense = _to_2d_tensor(cf_H_dense).cpu().float()

    diff = torch.abs(sub_dense - cf_dense)
    diff = (diff > 1e-5).float()

    num_diffs = torch.sum(diff).item()
    num_entries = torch.sum(sub_dense).item()

    return num_diffs, num_entries


def get_hyperedge_diff(sub_H_dense, cf_H_dense, eps=1e-5):
    """
    Counts how many hyperedges present in `sub_H_dense` were completely removed
    in `cf_H_dense`.

    Dense equivalent of src_sparse/evaluate.py:get_hyperedge_diff.

    Here, a hyperedge corresponds to a column having at least one nonzero entry.
    """
    sub_dense = _to_2d_tensor(sub_H_dense).cpu().float()
    cf_dense = _to_2d_tensor(cf_H_dense).cpu().float()

    if sub_dense.numel() == 0:
        return 0, 0

    sub_present = (sub_dense.abs() > eps).any(dim=0)
    cf_present = (
        (cf_dense.abs() > eps).any(dim=0)
        if cf_dense.numel()
        else torch.zeros_like(sub_present)
    )

    total_hyperedges = int(sub_present.sum().item())
    removed_hyperedges = int((sub_present & (~cf_present)).sum().item())

    return removed_hyperedges, total_hyperedges


def main():
    args = parse_args()

    if not os.path.exists(args.results):
        raise FileNotFoundError(f"Results file not found: {args.results}")

    with open(args.results, "rb") as f:
        cf_examples_per_node = pickle.load(f)

    header = [
        "node_idx",
        "new_idx",
        "cf_adj",
        "sub_adj",
        "y_pred_orig",
        "y_pred_new",
        "y_pred_new_actual",
        "label",
        "num_nodes",
        "loss_total",
        "loss_pred",
        "loss_graph_dist_training",
    ]

    df_prep = []
    total_attempts = len(cf_examples_per_node)

    for example in cf_examples_per_node:
        if example:
            df_prep.append(example[0])

    df = pd.DataFrame(df_prep, columns=header)

    if df.empty:
        print("No successful counterfactual examples found.")
        return

    graph_distances = []
    num_incidence_entries = []

    for i in df.index:
        cf_adj = df["cf_adj"][i]
        sub_adj = df["sub_adj"][i]

        if args.strategy == "v3":
            dist, entries = get_hyperedge_diff(sub_adj, cf_adj)
        else:
            dist, entries = get_incidence_diff(sub_adj, cf_adj)

        graph_distances.append(dist)
        num_incidence_entries.append(entries)

    df["graph_dist"] = graph_distances
    df["num_entries"] = num_incidence_entries

    print(args.results)
    print("Num cf examples found: {}/{}".format(len(df), total_attempts))

    print("Avg fidelity: {}".format(1 - len(df) / total_attempts))

    metric_name = "hyperedges removed" if args.strategy == "v3" else "entries changed"
    print(
        "Average graph distance ({}): {}, std: {}".format(
            metric_name, np.mean(df["graph_dist"]), np.std(df["graph_dist"])
        )
    )

    print(
        "Average sparsity: {}, std: {}".format(
            np.mean(1 - df["graph_dist"] / df["num_entries"]),
            np.std(1 - df["graph_dist"] / df["num_entries"]),
        )
    )

    print(" ")
    print("***************************************************************")
    print(" ")


if __name__ == "__main__":
    main()
